openapi: 3.0.0
info:
  title: "Devloom - Programming Education"
  description: "Devloom is a modular, scalable API designed for building a modern programming education platform. Built with TypeScript + Express + MongoDB + Zod, focusing on clarity, structure, and longâ€‘term maintainability."
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api/v1/'
    description: base url
tags:
  - name: "Auth"
    description: "User Auth"
  - name: "Category"
    description: "category of courses"
  - name: "Course"
    description: "courses"
  - name: "Lesson"
    description: "lessons of Course"
components:
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
      description: "accessToken Authorization: Bearer <accessToken>"
paths:
  /auth/signup:
    $ref: "./path/auth.yaml#/signup"