openapi: 3.0.0
info:
  title: "Devloom - Programming Education"
  description: "Devloom is a modular, scalable API designed for building a modern programming education platform. Built with TypeScript + Express + MongoDB + Zod, focusing on clarity, structure, and longâ€‘term maintainability."
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api/v1/'
    description: base url
tags:
  - name: "Auth"
    description: "User Auth"
  - name: "Category"
    description: "category of courses"
  - name: "Course"
    description: "courses"
  - name: "Lesson"
    description: "lessons of Course"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT access token"
security:
  - bearerAuth: [ ]
paths:
  /auth/signup:
    $ref: "./path/auth.yaml#/signup"
  /auth/login:
    $ref: "./path/auth.yaml#/login"
  /auth/getMe/:
    $ref: "./path/auth.yaml#/getMe"
  /auth/logout/:
    $ref: "./path/auth.yaml#/logout"