openapi: 3.1.0
info:
  title: "Devloom - Programming Education"
  summary: "A modern programming education platform API."
  description: "Devloom is a modular, scalable API designed for building a modern programming education platform. Built with TypeScript + Express + MongoDB + Zod, focusing on clarity, structure, and longâ€‘term maintainability."
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api/v1/'
    description: "base url"
tags:
  - name: "Auth"
    description: "User Auth"
  - name: "Category"
    description: "category of courses"
  - name: "Course"
    description: "courses"
  - name: "Lesson"
    description: "lessons of Course"
paths:
  "/auth/signup":
    post:
      operationId: "createUser"
      "summary": "create new user"
      description: "Create a new user in db collection(users)"
      tags:
        - "Auth"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: "string"
                  required: false
                  description: "name must be at least 3 characters and less than 20 characters"
                email:
                  type: "string"
                  required: true
                  format: "email"
                password:
                  type: "string"
                  required: true
                  format: "/^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]+$/"
                  description: "password must be at least 6 characters and contain at least one letter and one number"
              examples:
                name: "john"
                email: "john@mail.co"
                password: "123qwe"
      responses:
        201:
          description: "user created successfully"
          content:
            application/json:
              example:
                ok: true
                message: "Sign up successfully"
                user:
                  id: "695d0babedf79cffd1f83999"
                  name: "john"
                  email: "john@mail.co"
                  createdAt: "2026-01-06T13:18:35.169+0000"
                  updatedAt: "2026-01-06T13:18:35.169+0000"