openapi: 3.1.0
info:
  title: "Devloom - Programming Education"
  description: "Devloom is a modular, scalable API designed for building a modern programming education platform."
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api/v1/'
tags:
  - name: "Auth"
    description: "User Auth"
  - name: "Category"
    description: "category of courses"
  - name: "Course"
    description: "courses"
  - name: "Lesson"
    description: "lessons of Course"
paths:
  "/auth/signup":
    post:
      "summary": "create new user"
      tags:
        - "Auth"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: "string"
                  required: false
                  description: "name must be at least 3 characters and less than 20 characters"
                email:
                  type: "string"
                  required: true
                  format: "email"
                password:
                  type: "string"
                  required: true
                  format: "/^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]+$/"
                  description: "password must be at least 6 characters and contain at least one letter and one number"
      responses:
        200:
          description: "signup successfully"
          content:
            application/json:
              schema:
                name: "ali"
